apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
  labels:
    app: task-manager-api
data:
  SPRING_PROFILES_ACTIVE: "production"
  SERVER_PORT: "8080"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_TASKMANAGER: "DEBUG"
